import "server-only";

import { adminInbox, sendMail } from "@/lib/mail/transport";

/**
 * Member-facing email templates. English only, by design: transactional mail
 * that switches language with the in-app toggle becomes unreadable during an
 * incident, and the reset link is the one message that must be understood first
 * time.
 *
 * Each template ships a text/plain part as well as HTML, so a client that
 * blocks images still gets a usable link rather than an empty box.
 */

const GOLD = "#b08b3f";
const INK = "#191919";
const MUTED = "#6b6a66";
const LINE = "#e5e4df";
const PAPER = "#faf9f5";

function shell(heading: string, body: string): { html: string; text: string } {
  const html = `<!doctype html>
<html><body style="margin:0;padding:24px;background:${PAPER};font-family:Inter,Helvetica,Arial,sans-serif;color:${INK}">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">
    <table role="presentation" width="560" cellpadding="0" cellspacing="0" style="max-width:560px;background:#ffffff;border:1px solid ${LINE};border-radius:12px;overflow:hidden">
      <tr><td style="padding:28px 32px;border-bottom:1px solid ${LINE}">
        <span style="font-size:13px;font-weight:700;letter-spacing:.18em;text-transform:uppercase;color:${GOLD}">Fignal</span>
        <span style="font-size:13px;color:${MUTED}"> &nbsp;Platinum</span>
      </td></tr>
      <tr><td style="padding:32px">
        <h1 style="margin:0 0 14px;font-size:20px;line-height:1.3;font-weight:600">${heading}</h1>
        ${body}
      </td></tr>
      <tr><td style="padding:20px 32px;border-top:1px solid ${LINE};font-size:12px;color:${MUTED}">
        You are receiving this because you have a Fignal account.
      </td></tr>
    </table>
  </td></tr></table>
</body></html>`;

  const text = `Fignal Platinum\n\n${heading}\n\n${body.replace(/<[^>]+>/g, "").replace(/&amp;/g, "&").replace(/&nbsp;/g, " ").replace(/\s+/g, " ").trim()}\n`;
  return { html, text };
}

function button(href: string, label: string): string {
  return `<p style="margin:26px 0"><a href="${href}" style="display:inline-block;background:${INK};color:${PAPER};text-decoration:none;padding:12px 22px;border-radius:8px;font-size:14px;font-weight:600">${label}</a></p>
  <p style="margin:0;font-size:12px;color:${MUTED};word-break:break-all">If the button does not work, paste this link into your browser:<br>${href}</p>`;
}

/** Sent right after the Firebase account is created, before payment. */
export function accountActiveMail(username: string, loginUrl: string) {
  const { html, text } = shell(
    "Your Fignal account is active",
    `<p style="margin:0 0 8px;font-size:15px;line-height:1.6">Hello ${username}, your account has been created successfully.</p>
     <p style="margin:0;font-size:15px;line-height:1.6;color:${MUTED}">Sign in to complete your Platinum membership payment. Access unlocks as soon as the payment is verified - usually within a few seconds.</p>
     ${button(loginUrl, "Sign in")}`,
  );
  return {
    subject: "Your Fignal account is active",
    html,
    text,
  };
}

/** The link is generated by the Admin SDK so the mail provider stays ours. */
export function passwordResetMail(username: string, resetUrl: string) {
  const { html, text } = shell(
    "Reset your Fignal password",
    `<p style="margin:0 0 8px;font-size:15px;line-height:1.6">Hello ${username}, we received a request to reset your password.</p>
     <p style="margin:0;font-size:15px;line-height:1.6;color:${MUTED}">This link works once and expires in 60 minutes. If you did not ask for it, no action is needed - your password has not changed.</p>
     ${button(resetUrl, "Choose a new password")}`,
  );
  return {
    subject: "Reset your Fignal password",
    html,
    text,
  };
}

/** Sent by the QRIS webhook once a payment is verified, never by the client. */
export function paymentConfirmedMail(
  username: string,
  amountIdr: number,
  reference: string,
  dashboardUrl: string,
) {
  const rupiah = new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0,
  }).format(amountIdr);

  const { html, text } = shell(
    "Payment confirmed - Platinum is unlocked",
    `<p style="margin:0 0 8px;font-size:15px;line-height:1.6">Hello ${username}, we have received your payment and your Platinum access is now active.</p>
     <table role="presentation" cellpadding="0" cellspacing="0" style="margin:18px 0;font-size:14px;border-collapse:collapse">
       <tr><td style="padding:6px 20px 6px 0;color:${MUTED}">Amount</td><td style="padding:6px 0;font-weight:600">${rupiah}</td></tr>
       <tr><td style="padding:6px 20px 6px 0;color:${MUTED}">Reference</td><td style="padding:6px 0;font-family:ui-monospace,Menlo,monospace;font-size:13px">${reference}</td></tr>
     </table>
     ${button(dashboardUrl, "Open the dashboard")}`,
  );
  return {
    subject: "Payment confirmed - your Platinum access is active",
    html,
    text,
  };
}

/** Desk-owner alert. Not customer facing, so no link styling. */
export function adminAlertMail(subject: string, lines: string[]) {
  const { html, text } = shell(
    subject,
    lines.map((line) => `<p style="margin:0 0 6px;font-size:14px;line-height:1.6">${line}</p>`).join(""),
  );
  return { subject: `[Fignal] ${subject}`, html, text };
}

export async function mailAccountActive(username: string, email: string) {
  return sendMail({
    to: email,
    ...accountActiveMail(username, `${siteUrl()}/platinum`),
  });
}

export async function mailPasswordReset(username: string, email: string, resetUrl: string) {
  return sendMail({ to: email, ...passwordResetMail(username, resetUrl) });
}

export async function mailPaymentConfirmed(
  username: string,
  email: string,
  amountIdr: number,
  reference: string,
) {
  return sendMail({
    to: email,
    ...paymentConfirmedMail(username, amountIdr, reference, `${siteUrl()}/platinum`),
  });
}

export async function mailAdminAlert(subject: string, lines: string[]) {
  return sendMail({ to: adminInbox(), ...adminAlertMail(subject, lines) });
}

function siteUrl(): string {
  return (process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000").replace(/\/+$/, "");
}